name: Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the build'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE

          name=${{ github.event.inputs.name }}

          podman build --no-cache --format docker -t $GITHUB_REPOSITORY:$name ./$name/
