name: Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the build'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    outputs:
      IMAGE_DIGEST: ${{ steps.build.outputs.IMAGE_DIGEST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ github.event.inputs.name }}
        id: build
        run: |
          cd $GITHUB_WORKSPACE

          name=${{ github.event.inputs.name }}

          podman build --no-cache --format docker -t $GITHUB_REPOSITORY:$name ./$name/
          podman tag $GITHUB_REPOSITORY:$name $REGISTRY/$GITHUB_REPOSITORY:$name
          podman push $REGISTRY/$GITHUB_REPOSITORY:$name

          export IMAGE_DIGEST=$(podman inspect --format '{{.Digest}}' $GITHUB_REPOSITORY:$name)

          echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >> $GITHUB_OUTPUT
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.inputs.name }}
          subject-digest: ${{ needs.build.outputs.IMAGE_DIGEST }}
          push-to-registry: true
