name: Distribute

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          
          echo "Starting build"

          for name in $(git diff --name-only HEAD^ HEAD | awk -F/ '{print $1}' | sort -u); do
            if [[ $name == .* ]]; then
              continue
            fi

            if [ ! -d "./$name/" ]; then
              continue
            fi

            if [ -e "$name/Dockerfile" ]; then
              echo "Building $name"

              gh workflow run Build.yaml -f name=$name
            fi
          done
